version: "3.9"

services:
  db:
    image: postgres:15
    container_name: bitespeed-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bitespeed
    ports:
      - "5433:5432"

  app:
    build: .
    container_name: bitespeed-app
    restart: always
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      DATABASE_URL: postgresql://postgres:postgres@db:5432/bitespeed
    depends_on:
      - db